export const CATEGORY_CHANGE = 'CATEGORY_CHANGE';
export const EDIT_PRODUCT_NAME = 'EDIT_PRODUCT_NAME';
export const EDIT_PRODUCT_PRICE = 'EDIT_PRODUCT_PRICE';
export const EDIT_PRODUCT_QUANTITY = 'EDIT_PRODUCT_QUANTITY';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT'